using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;


namespace YumaPos.SourceGenerators.GenerateResponseDto;

// https://habr.com/ru/articles/731310/
[Generator]
public class GenerateResponseDtoGenerator : IIncrementalGenerator
{
    private const string AttributeShortName = "GenerateResponseDto";
    private const string AttributeFullName = AttributeShortName + "Attribute";
    private const string AttributeTypeName = "YumaPos.Shared.Infrastructure.Attributes." + AttributeFullName;
    private const string ConfigFileName = "generatorconfig.json";
    
    
    private static readonly DiagnosticDescriptor NonPublicTypesAreNotSupported =
        new(
            "TS0001",
            "Non-public types types are not supported",
            "Change the visibility of type '{0}' to public",
            "category",
            DiagnosticSeverity.Error,
            true);
    
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var comparer = TypeComparer.Instance;
        var pipeline =
            context.SyntaxProvider.CreateSyntaxProvider(
                    (node, _) => NodePredicate(node),
                    TargetFactory)
               .Where(target => target is not null)! 
               .WithComparer(comparer) 
               .Collect()
               .SelectMany((targets, _) => targets.Distinct(comparer))
               .Collect();
        
        var configProvider = context.AdditionalTextsProvider
           .Where(file => Path.GetFileName(file.Path).Equals(ConfigFileName, StringComparison.OrdinalIgnoreCase))
           .Select((file, ct) => ParseConfig(file.GetText(ct)))
           .Collect();

        context.RegisterSourceOutput(
            pipeline.Combine(configProvider),
            (spc, combined) => GenerateCode(spc, combined.Left, combined.Right));
    }

    private void GenerateCode(SourceProductionContext context, ImmutableArray<BuilderTarget> classesWithAttribute, ImmutableArray<ResponseGeneratorConfig?> configFiles)
    {
        var config1 = configFiles.FirstOrDefault() ?? ResponseGeneratorConfig.Default;
        var outputNamespace = config1.OutputNamespace;
        var containingNamespaces = new HashSet<string>();
        var sourceClassNamesWithoutDtoSuffix = new List<(string sourceClassNameWithoutDtoSuffix, string sourceClassName)>();
        foreach (var target in classesWithAttribute)
        {
            if (target.Type.DeclaredAccessibility != Accessibility.Public)
            {
                var diagnostic = Diagnostic.Create(
                    NonPublicTypesAreNotSupported,
                    target.Declaration.Keyword.GetLocation(),
                    target.Type); 
                context.ReportDiagnostic(diagnostic);
                continue;
            }
            var containingNamespace = target.Type.ContainingNamespace;
            var sourceClassName = target.Type.Name;
            var sourceClassNameWithoutDtoSuffix = sourceClassName.EndsWith("Dto", StringComparison.OrdinalIgnoreCase)
                ? sourceClassName.Substring(0, sourceClassName.Length - 3) 
                : sourceClassName;
            containingNamespaces.Add(containingNamespace.ToString());
            sourceClassNamesWithoutDtoSuffix.Add((sourceClassNameWithoutDtoSuffix, sourceClassName));
        }
        var sb = new StringBuilder();
        sb.Append($"""
                   // <auto-generated by {nameof(GenerateResponseDtoGenerator)}/>
                   
                   using System;
                   using System.Collections.Generic;
                   using YumaPos.Shared.API.ResponseDtos;
                   
                   """);
        foreach (var containingNamespace in containingNamespaces.OrderBy(x=>x))
        {
            sb.AppendLine($"using {containingNamespace};");
        }
        
        sb.AppendLine();
        
        sb.AppendLine($"namespace {outputNamespace};");
        foreach (var names in sourceClassNamesWithoutDtoSuffix.OrderBy(x=>x))
        {
            sb.AppendLine($"public class {names.sourceClassNameWithoutDtoSuffix}ResponseDto: ResponseDtoWithValue<{names.sourceClassName}>{{}}");
            sb.AppendLine($"public class {names.sourceClassNameWithoutDtoSuffix}ListResponseDto: ResponseDtoWithValue<IEnumerable<{names.sourceClassName}>>{{}}");
            sb.AppendLine();
        }
        
        context.AddSource($"ResponseDtos.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static BuilderTarget? TargetFactory(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var declaration = (ClassDeclarationSyntax)context.Node.Parent!.Parent!; // F1
        return context.SemanticModel
                  .GetDeclaredSymbol(declaration, cancellationToken) is INamedTypeSymbol type // F2
            && type.GetAttributes()
                  .Any(attr => attr.AttributeClass?.ToDisplayString(NullableFlowState.None) == AttributeTypeName) // F3
            ? new BuilderTarget(declaration, type)
            : null;
    }
    private sealed record BuilderTarget
    {
        public BuilderTarget(ClassDeclarationSyntax declaration, INamedTypeSymbol type)
        {
            Declaration = declaration;
            Type = type;
        }
        public ClassDeclarationSyntax Declaration { get; set; }
        public INamedTypeSymbol Type { get; set; }
    }
    private static bool NodePredicate(SyntaxNode node)
        => node is AttributeSyntax attribute
        && GetNameText(attribute.Name) is AttributeShortName or AttributeFullName
        && !ContainsErrors(attribute)
        && attribute.Parent?.Parent is ClassDeclarationSyntax;
    
    private static bool ContainsErrors(CSharpSyntaxNode node)
        => node
           .GetDiagnostics()
           .Any(d => d.Severity == DiagnosticSeverity.Error);
    private static string? GetNameText(NameSyntax? name)
        => name switch
        {
            SimpleNameSyntax ins => ins.Identifier.Text,
            QualifiedNameSyntax qns => qns.Right.Identifier.Text,
            _ => null,
        };
    private static ResponseGeneratorConfig? ParseConfig(SourceText? sourceText)
    {
        if (sourceText?.ToString().Trim().Length == 0)
            return ResponseGeneratorConfig.Default;

        try
        {
            var json = sourceText.ToString();
            var doc = JsonDocument.Parse(json);
            var config = doc.Deserialize<ResponseGeneratorConfig>(new JsonSerializerOptions(){UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow});
            return config;
        }
        catch
        {
            return ResponseGeneratorConfig.Default;
        }
    }
   
    private sealed class TypeComparer : IEqualityComparer<BuilderTarget>
    {
        private TypeComparer()
        {
        }

        public static TypeComparer Instance { get; } = new();

        public bool Equals(BuilderTarget x, BuilderTarget y)
            => x.Type.Equals(y.Type, SymbolEqualityComparer.IncludeNullability);

        public int GetHashCode(BuilderTarget obj)
            => SymbolEqualityComparer.IncludeNullability.GetHashCode(obj.Type);
    }
}