//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.Collections.Generic; 
using System.ServiceModel; 
using System.Threading.Tasks; 
 

namespace TestWcfClientGenerator
 { 
	 [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	 [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IWcfServiceClient")]
	 public interface IWcfServiceClient
 	{ 
		 bool IsCaughtException { get; set; } 

		 [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IWcfService/AddItem", ReplyAction = "http://tempuri.org/IWcfService/AddItemResponse")]
		 System.IAsyncResult BeginAddItem(Guid id, string name, System.AsyncCallback callback, object asyncState);

		 TestDecoratorGeneration.ResponseDto EndAddItem(System.IAsyncResult result);

		 [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IWcfService/GetItems", ReplyAction = "http://tempuri.org/IWcfService/GetItemsResponse")]
		 System.IAsyncResult BeginGetItems(System.AsyncCallback callback, object asyncState);

		 TestDecoratorGeneration.ItemDto[] EndGetItems(System.IAsyncResult result);

		 [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IWcfService/Open", ReplyAction = "http://tempuri.org/IWcfService/OpenResponse")]
		 System.IAsyncResult BeginOpen(System.AsyncCallback callback, object asyncState);

		 void EndOpen(System.IAsyncResult result);

	 } 

	 [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	 public interface IWcfServiceChannel : IWcfServiceClient, System.ServiceModel.IClientChannel{} 
 }