//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated from a template.
//
//	 Manual changes to this file may cause unexpected behavior in your application.
//	 Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace TestDecoratorGeneration
{
	public partial class ServiceDecorator
	{

		private TestDecoratorGeneration.Service DecoratedComponent { get; set; }

		public async System.Threading.Tasks.Task Open()
		{
			try
			{
				await InitAsync("Open", new object[] { });
				OnEntry();
				await DecoratedComponent.Open();
				OnExit();
			}
			catch (System.Exception e)
			{
				OnException(e);
			}
			finally
			{
				OnFinally();
			}
		}
		public async System.Threading.Tasks.Task<TestDecoratorGeneration.ResponseDto> AddItem(System.Guid id, System.String name)
		{
			TestDecoratorGeneration.ResponseDto ret = null;
			try
			{
				await InitAsync("AddItem", new object[] { id, name });
				OnEntry();
				ret = await DecoratedComponent.AddItem(id, name);
				OnExit();
			}
			catch (System.Exception e)
			{
				OnException(e);
			}
			finally
			{
				OnFinally();
			}
			return ret;
		}
		public async System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<TestDecoratorGeneration.ItemDto>> GetItems()
		{
			System.Collections.Generic.IEnumerable<TestDecoratorGeneration.ItemDto> ret = null;
			try
			{
				await InitAsync("GetItems", new object[] { });
				OnEntry();
				ret = await DecoratedComponent.GetItems();
				OnExit();
			}
			catch (System.Exception e)
			{
				OnException(e);
			}
			finally
			{
				OnFinally();
			}
			return ret;
		}
		public void Stop()
		{
			try
			{
				Init("Stop", new object[] { });
				OnEntry();
				DecoratedComponent.Stop();
				OnExit();
			}
			catch (System.Exception e)
			{
				OnException(e);
			}
			finally
			{
				OnFinally();
			}
		}
		public System.Guid GetGuid()
		{
			System.Guid ret = default(System.Guid);
			try
			{
				Init("GetGuid", new object[] { });
				OnEntry();
				ret = DecoratedComponent.GetGuid();
				OnExit();
			}
			catch (System.Exception e)
			{
				OnException(e);
			}
			finally
			{
				OnFinally();
			}
			return ret;
		}
		public int GetInt()
		{
			int ret = default(int);
			try
			{
				Init("GetInt", new object[] { });
				OnEntry();
				ret = DecoratedComponent.GetInt();
				OnExit();
			}
			catch (System.Exception e)
			{
				OnException(e);
			}
			finally
			{
				OnFinally();
			}
			return ret;
		}

	}
}
