using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.Text;

namespace WCFGenerator.Common
{
    internal static class CodeHelper
    {
        public const string GeneratedDocumentHeader =
            """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated from a template.
            //
            //     Manual changes to this file may cause unexpected behavior in your application.
            //     Manual changes to this file will be overwritten if the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            """;

        public static async Task AddDocument(bool standartFormatting, Project project, string fileName, string code, string[] folders)
        {
            var document = project.AddDocument(fileName, code, folders);
            if (standartFormatting)
            {
                document = await Format(document);
            }

            // this is workaround to Roslyn adding strings <Compile Include="Repositories\Generated\CashDrawerCheckRepository.g.cs" />
            // to a project file if add file directly to Roslyn
            var documentText = (await document.GetTextAsync()).ToString();
            var lastOccur = project.FilePath.Split(new[] { '\\' }).Last().Length;
            var path = project.FilePath.Substring(0, project.FilePath.Length - lastOccur) + String.Join(@"\", folders) + @"\" + fileName;
            await System.IO.File.WriteAllTextAsync(path, documentText, Encoding.UTF8);
        }

        public static async Task<Document> Format(Document doc)
        {
            // general format
            var formattedDoc = await Formatter.FormatAsync(doc);
            var text = (await formattedDoc.GetTextAsync()).ToString().Replace("    ", "\t");
            formattedDoc = formattedDoc.WithText(SourceText.From(text));
            return formattedDoc;
        }
    }
}