namespace WCFGenerator.Common
{
    internal static class CodeHelper
    {
        public static string GeneratedDocumentHeader =
                  "//------------------------------------------------------------------------------\r\n"
                + "// <auto-generated>\r\n"
                + "//     This code was generated from a template.\r\n"
                + "//\r\n"
                + "//     Manual changes to this file may cause unexpected behavior in your application.\r\n"
                + "//     Manual changes to this file will be overwritten if the code is regenerated.\r\n"
                + "// </auto-generated>\r\n"
                + "//------------------------------------------------------------------------------\r\n";
    }
}