//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated from a template.
//
//	 Manual changes to this file may cause unexpected behavior in your application.
//	 Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Globalization;
using TestRepositoryGeneration.RepositoryInterfaces;


namespace TestRepositoryGeneration
{
	public partial class AddressArchiveRepository : TestRepositoryGeneration.Infrastructure.RepositoryBase, TestRepositoryGeneration.RepositoryInterfaces.IAddressArchiveRepository
	{
		public const string Fields = @"archive.addresses.id,archive.addresses.country,archive.addresses.city,archive.addresses.state,archive.addresses.street,archive.addresses.building,archive.addresses.zip_code,archive.addresses.latitude,archive.addresses.longitude,archive.addresses.created,archive.addresses.modified,archive.addresses.expire_date,archive.addresses.sync_state";
		private const string SelectAllQuery = @"SELECT archive.addresses.id,archive.addresses.country,archive.addresses.city,archive.addresses.state,archive.addresses.street,archive.addresses.building,archive.addresses.zip_code,archive.addresses.latitude,archive.addresses.longitude,archive.addresses.created,archive.addresses.modified,archive.addresses.expire_date,archive.addresses.sync_state FROM archive.addresses   ";
		private const string SelectByQuery = @"SELECT archive.addresses.id,archive.addresses.country,archive.addresses.city,archive.addresses.state,archive.addresses.street,archive.addresses.building,archive.addresses.zip_code,archive.addresses.latitude,archive.addresses.longitude,archive.addresses.created,archive.addresses.modified,archive.addresses.expire_date,archive.addresses.sync_state FROM archive.addresses ";
		private const string InsertQuery = @"INSERT INTO archive.addresses(archive.addresses.id,archive.addresses.country,archive.addresses.city,archive.addresses.state,archive.addresses.street,archive.addresses.building,archive.addresses.zip_code,archive.addresses.latitude,archive.addresses.longitude,archive.addresses.created,archive.addresses.modified,archive.addresses.expire_date,archive.addresses.sync_state) OUTPUT INSERTED.Id VALUES(@Id,@Country,@City,@State,@Street,@Building,@ZipCode,@Latitude,@Longitude,@Created,@Modified,@ExpireDate,@SyncState) ";
		private const string UpdateQueryBy = @"UPDATE archive.addresses SET archive.addresses.id = @Id,archive.addresses.country = @Country,archive.addresses.city = @City,archive.addresses.state = @State,archive.addresses.street = @Street,archive.addresses.building = @Building,archive.addresses.zip_code = @ZipCode,archive.addresses.latitude = @Latitude,archive.addresses.longitude = @Longitude,archive.addresses.created = @Created,archive.addresses.modified = @Modified,archive.addresses.expire_date = @ExpireDate,archive.addresses.sync_state = @SyncState FROM archive.addresses ";
		private const string DeleteQueryBy = @"UPDATE archive.addresses SET is_deleted = TRUE ";
		private const string InsertOrUpdateQuery = @"INSERT INTO archive.addresses(archive.addresses.id,archive.addresses.country,archive.addresses.city,archive.addresses.state,archive.addresses.street,archive.addresses.building,archive.addresses.zip_code,archive.addresses.latitude,archive.addresses.longitude,archive.addresses.created,archive.addresses.modified,archive.addresses.expire_date,archive.addresses.sync_state) OUTPUT INSERTED.Id VALUES(@Id,@Country,@City,@State,@Street,@Building,@ZipCode,@Latitude,@Longitude,@Created,@Modified,@ExpireDate,@SyncState)  ON CONFLICT (id) DO UPDATE archive.addresses SET archive.addresses.id = @Id,archive.addresses.country = @Country,archive.addresses.city = @City,archive.addresses.state = @State,archive.addresses.street = @Street,archive.addresses.building = @Building,archive.addresses.zip_code = @ZipCode,archive.addresses.latitude = @Latitude,archive.addresses.longitude = @Longitude,archive.addresses.created = @Created,archive.addresses.modified = @Modified,archive.addresses.expire_date = @ExpireDate,archive.addresses.sync_state = @SyncState ";
		private const string UpdateManyByIdQueryTemplate = @"GenerateUpdateMany script was not generated";
		private const string WhereQueryById = "WHERE archive.addresses.id = @Id ";
		private const string WhereQueryByModified = "WHERE archive.addresses.modified >= @startModified AND archive.addresses.modified < @endModified ";
		private const string WhereQueryByCountryAndCity = "WHERE archive.addresses.country = @Country AND archive.addresses.city = @City ";
		private const string WhereQueryByCountryAndCityAndZipCode = "WHERE archive.addresses.country = @Country AND archive.addresses.city = @City AND archive.addresses.zip_code = @ZipCode ";
		private const string AndWithIsDeletedFilter = "AND archive.addresses.is_deleted = @IsDeleted ";
		private const string WhereWithIsDeletedFilter = "WHERE archive.addresses.is_deleted = @IsDeleted ";
		private const string InsertManyQueryTemplate = @"InsertMany script was not generated";
		private const string InsertManyValuesTemplate = @"InsertMany script was not generated";



		public AddressArchiveRepository(TestRepositoryGeneration.Infrastructure.IDataAccessService dataAccessService, TestRepositoryGeneration.Infrastructure.IDataAccessController dataAccessController) : base(dataAccessService, dataAccessController) { }
		public IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> GetAll(bool? isDeleted = false)
		{
			var sql = SelectAllQuery;
			object parameters = new { isDeleted };
			if (isDeleted.HasValue)
			{
				sql = sql + WhereWithIsDeletedFilter;
			}
			var result = DataAccessService.Get<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters).ToList();
			return result.ToList();
		}
		public async Task<IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>> GetAllAsync(bool? isDeleted = false)
		{
			var sql = SelectAllQuery;
			object parameters = new { isDeleted };
			if (isDeleted.HasValue)
			{
				sql = sql + WhereWithIsDeletedFilter;
			}
			var result = (await DataAccessService.GetAsync<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters));
			return result.ToList();
		}

		public TestRepositoryGeneration.DataObjects.BaseRepositories.Address GetById(System.Guid id, bool? isDeleted = false)
		{
			object parameters = new { id, isDeleted };
			var sql = SelectByQuery + WhereQueryById;
			if (isDeleted.HasValue)
			{
				sql = sql + AndWithIsDeletedFilter;
			}
			var result = DataAccessService.Get<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters);
			return result.FirstOrDefault();
		}
		public async Task<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> GetByIdAsync(System.Guid id, bool? isDeleted = false)
		{
			object parameters = new { id, isDeleted };
			var sql = SelectByQuery + WhereQueryById;
			if (isDeleted.HasValue)
			{
				sql = sql + AndWithIsDeletedFilter;
			}
			var result = (await DataAccessService.GetAsync<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters));
			return result.FirstOrDefault();
		}


		/*
		public IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> GetByModified(System.DateTime startModified, System.DateTime endModified, bool? isDeleted = false)
		{
		object parameters = new {startModified, endModified, isDeleted};
		var sql = SelectByQuery + WhereQueryByModified;
		if (isDeleted.HasValue)
		{
		sql = sql + AndWithIsDeletedFilter;
		}
		var result = DataAccessService.Get<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters);
		return result.ToList();
		}
		public async Task<IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>> GetByModifiedAsync(System.DateTime startModified, System.DateTime endModified, bool? isDeleted = false)
		{
		object parameters = new {startModified, endModified, isDeleted};
		var sql = SelectByQuery + WhereQueryByModified;
		if (isDeleted.HasValue)
		{
		sql = sql + AndWithIsDeletedFilter;
		}
		var result = (await DataAccessService.GetAsync<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters));
		return result.ToList();
		}


		*/
		public TestRepositoryGeneration.DataObjects.BaseRepositories.Address GetByCountryAndCity(string country, string city, bool? isDeleted = false)
		{
			object parameters = new { country, city, isDeleted };
			var sql = SelectByQuery + WhereQueryByCountryAndCity;
			if (isDeleted.HasValue)
			{
				sql = sql + AndWithIsDeletedFilter;
			}
			var result = DataAccessService.Get<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters);
			return result.FirstOrDefault();
		}
		public async Task<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> GetByCountryAndCityAsync(string country, string city, bool? isDeleted = false)
		{
			object parameters = new { country, city, isDeleted };
			var sql = SelectByQuery + WhereQueryByCountryAndCity;
			if (isDeleted.HasValue)
			{
				sql = sql + AndWithIsDeletedFilter;
			}
			var result = (await DataAccessService.GetAsync<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters));
			return result.FirstOrDefault();
		}

		public TestRepositoryGeneration.DataObjects.BaseRepositories.Address GetByCountryAndCityAndZipCode(string country, string city, string zipCode, bool? isDeleted = false)
		{
			object parameters = new { country, city, zipCode, isDeleted };
			var sql = SelectByQuery + WhereQueryByCountryAndCityAndZipCode;
			if (isDeleted.HasValue)
			{
				sql = sql + AndWithIsDeletedFilter;
			}
			var result = DataAccessService.Get<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters);
			return result.FirstOrDefault();
		}
		public async Task<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> GetByCountryAndCityAndZipCodeAsync(string country, string city, string zipCode, bool? isDeleted = false)
		{
			object parameters = new { country, city, zipCode, isDeleted };
			var sql = SelectByQuery + WhereQueryByCountryAndCityAndZipCode;
			if (isDeleted.HasValue)
			{
				sql = sql + AndWithIsDeletedFilter;
			}
			var result = (await DataAccessService.GetAsync<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters));
			return result.FirstOrDefault();
		}


		public void Insert(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
			DataAccessService.InsertObject(address, InsertQuery);
		}
		public async Task InsertAsync(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
			await DataAccessService.InsertObjectAsync(address, InsertQuery);
		}

		/*

		public void InsertMany(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxInsertManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxInsertManyRows = maxInsertManyRowsWithParameters < MaxInsertManyRows 
																? maxInsertManyRowsWithParameters
																: MaxInsertManyRows;
		var values = new System.Text.StringBuilder();
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxInsertManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 

		foreach (var items in itemsPerRequest)
		{
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		values.AppendLine(index != 0 ? ",":"");
		values.AppendFormat(InsertManyValuesTemplate, index, address.Id,address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Created.ToString(CultureInfo.InvariantCulture),address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendFormat(InsertManyQueryTemplate, values.Replace("'NULL'","NULL").ToString());
		DataAccessService.Execute(query.ToString(), parameters);
		parameters.Clear();
		values.Clear();
		query.Clear();
		}

		}

		public void InsertManySplitByTransactions(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxInsertManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxInsertManyRows = maxInsertManyRowsWithParameters < MaxInsertManyRows 
																? maxInsertManyRowsWithParameters
																: MaxInsertManyRows;
		var values = new System.Text.StringBuilder();
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxInsertManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 

		foreach (var items in itemsPerRequest)
		{
		query.AppendLine("BEGIN TRANSACTION;");
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		values.AppendLine(index != 0 ? ",":"");
		values.AppendFormat(InsertManyValuesTemplate, index, address.Id,address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Created.ToString(CultureInfo.InvariantCulture),address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendFormat(InsertManyQueryTemplate, values.Replace("'NULL'","NULL").ToString());
		query.AppendLine("COMMIT TRANSACTION;");
		DataAccessService.Execute(query.ToString(), parameters);
		parameters.Clear();
		values.Clear();
		query.Clear();
		}

		}

		public async Task InsertManyAsync(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxInsertManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxInsertManyRows = maxInsertManyRowsWithParameters < MaxInsertManyRows 
																? maxInsertManyRowsWithParameters
																: MaxInsertManyRows;
		var values = new System.Text.StringBuilder();
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxInsertManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 

		await Task.Delay(10);

		foreach (var items in itemsPerRequest)
		{
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		values.AppendLine(index != 0 ? ",":"");
		values.AppendFormat(InsertManyValuesTemplate, index, address.Id,address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Created.ToString(CultureInfo.InvariantCulture),address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendFormat(InsertManyQueryTemplate, values.Replace("'NULL'","NULL").ToString());

		await Task.Delay(10);
		await DataAccessService.ExecuteAsync(query.ToString(), parameters);
		parameters.Clear();
		values.Clear();
		query.Clear();
		}

		await Task.Delay(10);

		}

		public async Task InsertManySplitByTransactionsAsync(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxInsertManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxInsertManyRows = maxInsertManyRowsWithParameters < MaxInsertManyRows 
																? maxInsertManyRowsWithParameters
																: MaxInsertManyRows;
		var values = new System.Text.StringBuilder();
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxInsertManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 

		await Task.Delay(10);

		foreach (var items in itemsPerRequest)
		{
		query.AppendLine("BEGIN TRANSACTION;");
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		values.AppendLine(index != 0 ? ",":"");
		values.AppendFormat(InsertManyValuesTemplate, index, address.Id,address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Created.ToString(CultureInfo.InvariantCulture),address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendFormat(InsertManyQueryTemplate, values.Replace("'NULL'","NULL").ToString());
		query.AppendLine("COMMIT TRANSACTION;");

		await Task.Delay(10);
		await DataAccessService.ExecuteAsync(query.ToString(), parameters);
		parameters.Clear();
		values.Clear();
		query.Clear();
		}

		await Task.Delay(10);

		}

		*/
		public void UpdateById(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
			var sql = UpdateQueryBy + WhereQueryById;
			DataAccessService.PersistObject(address, sql);
		}
		public async Task UpdateByIdAsync(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
			var sql = UpdateQueryBy + WhereQueryById;
			await DataAccessService.PersistObjectAsync(address, sql);
		}

		/*
		public void UpdateByCountryAndCity(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
		var sql = UpdateQueryBy + WhereQueryByCountryAndCity; 
		DataAccessService.PersistObject(address, sql);
		}
		public async Task UpdateByCountryAndCityAsync(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
		var sql = UpdateQueryBy + WhereQueryByCountryAndCity; 
		await DataAccessService.PersistObjectAsync(address, sql);
		}


		*//*
		public void UpdateByCountryAndCityAndZipCode(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
		var sql = UpdateQueryBy + WhereQueryByCountryAndCityAndZipCode; 
		DataAccessService.PersistObject(address, sql);
		}
		public async Task UpdateByCountryAndCityAndZipCodeAsync(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
		var sql = UpdateQueryBy + WhereQueryByCountryAndCityAndZipCode; 
		await DataAccessService.PersistObjectAsync(address, sql);
		}


		*/
		/*

		public void UpdateManyByIdSplitByTransactions(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxUpdateManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxUpdateManyRows = maxUpdateManyRowsWithParameters < MaxUpdateManyRows 
																? maxUpdateManyRowsWithParameters
																: MaxUpdateManyRows;
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxUpdateManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 


		foreach (var items in itemsPerRequest)
		{
		query.AppendLine("BEGIN TRANSACTION");
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Id{index}", address.Id);
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		query.AppendFormat($"{UpdateManyByIdQueryTemplate};", index, address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendLine("COMMIT TRANSACTION");
		var fullSqlStatement = DataAccessService.GenerateFullSqlStatement(query.ToString().Replace("'NULL'", "NULL"), typeof(TestRepositoryGeneration.DataObjects.BaseRepositories.Address));
		DataAccessService.Execute(fullSqlStatement.ToString(), parameters);
		parameters.Clear();
		query.Clear();
		}


		}

		public async Task UpdateManyByIdSplitByTransactionsAsync(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxUpdateManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxUpdateManyRows = maxUpdateManyRowsWithParameters < MaxUpdateManyRows 
																? maxUpdateManyRowsWithParameters
																: MaxUpdateManyRows;
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxUpdateManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 

		await Task.Delay(10);

		foreach (var items in itemsPerRequest)
		{
		query.AppendLine("BEGIN TRANSACTION");
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Id{index}", address.Id);
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		query.AppendFormat($"{UpdateManyByIdQueryTemplate};", index, address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendLine("COMMIT TRANSACTION");
		await Task.Delay(10);
		var fullSqlStatement = DataAccessService.GenerateFullSqlStatement(query.ToString().Replace("'NULL'", "NULL"), typeof(TestRepositoryGeneration.DataObjects.BaseRepositories.Address));
		await DataAccessService.ExecuteAsync(fullSqlStatement.ToString(), parameters);
		parameters.Clear();
		query.Clear();
		}

		await Task.Delay(10);

		}

		*//*

		public void UpdateManyByModifiedSplitByTransactions(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxUpdateManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxUpdateManyRows = maxUpdateManyRowsWithParameters < MaxUpdateManyRows 
																? maxUpdateManyRowsWithParameters
																: MaxUpdateManyRows;
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxUpdateManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 


		foreach (var items in itemsPerRequest)
		{
		query.AppendLine("BEGIN TRANSACTION");
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Modified{index}", address.Modified);
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		query.AppendFormat($"{UpdateManyByIdQueryTemplate};", index, address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendLine("COMMIT TRANSACTION");
		var fullSqlStatement = DataAccessService.GenerateFullSqlStatement(query.ToString().Replace("'NULL'", "NULL"), typeof(TestRepositoryGeneration.DataObjects.BaseRepositories.Address));
		DataAccessService.Execute(fullSqlStatement.ToString(), parameters);
		parameters.Clear();
		query.Clear();
		}


		}

		public async Task UpdateManyByModifiedSplitByTransactionsAsync(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxUpdateManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxUpdateManyRows = maxUpdateManyRowsWithParameters < MaxUpdateManyRows 
																? maxUpdateManyRowsWithParameters
																: MaxUpdateManyRows;
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxUpdateManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 

		await Task.Delay(10);

		foreach (var items in itemsPerRequest)
		{
		query.AppendLine("BEGIN TRANSACTION");
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Modified{index}", address.Modified);
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		query.AppendFormat($"{UpdateManyByIdQueryTemplate};", index, address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendLine("COMMIT TRANSACTION");
		await Task.Delay(10);
		var fullSqlStatement = DataAccessService.GenerateFullSqlStatement(query.ToString().Replace("'NULL'", "NULL"), typeof(TestRepositoryGeneration.DataObjects.BaseRepositories.Address));
		await DataAccessService.ExecuteAsync(fullSqlStatement.ToString(), parameters);
		parameters.Clear();
		query.Clear();
		}

		await Task.Delay(10);

		}

		*//*

		public void UpdateManyByCountryAndCitySplitByTransactions(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxUpdateManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxUpdateManyRows = maxUpdateManyRowsWithParameters < MaxUpdateManyRows 
																? maxUpdateManyRowsWithParameters
																: MaxUpdateManyRows;
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxUpdateManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 


		foreach (var items in itemsPerRequest)
		{
		query.AppendLine("BEGIN TRANSACTION");
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		query.AppendFormat($"{UpdateManyByIdQueryTemplate};", index, address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendLine("COMMIT TRANSACTION");
		var fullSqlStatement = DataAccessService.GenerateFullSqlStatement(query.ToString().Replace("'NULL'", "NULL"), typeof(TestRepositoryGeneration.DataObjects.BaseRepositories.Address));
		DataAccessService.Execute(fullSqlStatement.ToString(), parameters);
		parameters.Clear();
		query.Clear();
		}


		}

		public async Task UpdateManyByCountryAndCitySplitByTransactionsAsync(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxUpdateManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxUpdateManyRows = maxUpdateManyRowsWithParameters < MaxUpdateManyRows 
																? maxUpdateManyRowsWithParameters
																: MaxUpdateManyRows;
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxUpdateManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 

		await Task.Delay(10);

		foreach (var items in itemsPerRequest)
		{
		query.AppendLine("BEGIN TRANSACTION");
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		query.AppendFormat($"{UpdateManyByIdQueryTemplate};", index, address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendLine("COMMIT TRANSACTION");
		await Task.Delay(10);
		var fullSqlStatement = DataAccessService.GenerateFullSqlStatement(query.ToString().Replace("'NULL'", "NULL"), typeof(TestRepositoryGeneration.DataObjects.BaseRepositories.Address));
		await DataAccessService.ExecuteAsync(fullSqlStatement.ToString(), parameters);
		parameters.Clear();
		query.Clear();
		}

		await Task.Delay(10);

		}

		*//*

		public void UpdateManyByCountryAndCityAndZipCodeSplitByTransactions(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxUpdateManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxUpdateManyRows = maxUpdateManyRowsWithParameters < MaxUpdateManyRows 
																? maxUpdateManyRowsWithParameters
																: MaxUpdateManyRows;
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxUpdateManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 


		foreach (var items in itemsPerRequest)
		{
		query.AppendLine("BEGIN TRANSACTION");
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		query.AppendFormat($"{UpdateManyByIdQueryTemplate};", index, address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendLine("COMMIT TRANSACTION");
		var fullSqlStatement = DataAccessService.GenerateFullSqlStatement(query.ToString().Replace("'NULL'", "NULL"), typeof(TestRepositoryGeneration.DataObjects.BaseRepositories.Address));
		DataAccessService.Execute(fullSqlStatement.ToString(), parameters);
		parameters.Clear();
		query.Clear();
		}


		}

		public async Task UpdateManyByCountryAndCityAndZipCodeSplitByTransactionsAsync(IEnumerable<TestRepositoryGeneration.DataObjects.BaseRepositories.Address> addressList)
		{
		if(addressList==null) throw new ArgumentException(nameof(addressList));

		if(!addressList.Any()) return;

		var maxUpdateManyRowsWithParameters = MaxRepositoryParams / 6;
		var maxUpdateManyRows = maxUpdateManyRowsWithParameters < MaxUpdateManyRows 
																? maxUpdateManyRowsWithParameters
																: MaxUpdateManyRows;
		var query = new System.Text.StringBuilder();
		var parameters = new Dictionary<string, object>();

		var itemsPerRequest = addressList.Select((x, i) => new {Index = i,Value = x})
						.GroupBy(x => x.Index / maxUpdateManyRows)
						.Select(x => x.Select((v, i) => new { Index = i, Value = v.Value }).ToList())
						.ToList(); 

		await Task.Delay(10);

		foreach (var items in itemsPerRequest)
		{
		query.AppendLine("BEGIN TRANSACTION");
		foreach (var item in items)
		{
		var address = item.Value;
		var index = item.Index; 
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		parameters.Add($"Country{index}", address.Country);
		parameters.Add($"City{index}", address.City);
		parameters.Add($"State{index}", address.State);
		parameters.Add($"Street{index}", address.Street);
		parameters.Add($"Building{index}", address.Building);
		parameters.Add($"ZipCode{index}", address.ZipCode);
		query.AppendFormat($"{UpdateManyByIdQueryTemplate};", index, address.Latitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Longitude?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.Modified.ToString(CultureInfo.InvariantCulture),address.ExpireDate?.ToString(CultureInfo.InvariantCulture) ?? "NULL",address.SyncState ? 1 : 0);
		}
		query.AppendLine("COMMIT TRANSACTION");
		await Task.Delay(10);
		var fullSqlStatement = DataAccessService.GenerateFullSqlStatement(query.ToString().Replace("'NULL'", "NULL"), typeof(TestRepositoryGeneration.DataObjects.BaseRepositories.Address));
		await DataAccessService.ExecuteAsync(fullSqlStatement.ToString(), parameters);
		parameters.Clear();
		query.Clear();
		}

		await Task.Delay(10);

		}

		*/
		public void RemoveById(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
			var sql = DeleteQueryBy + WhereQueryById;
			DataAccessService.PersistObject(address, sql);
		}
		public async Task RemoveByIdAsync(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
			var sql = DeleteQueryBy + WhereQueryById;
			await DataAccessService.PersistObjectAsync(address, sql);
		}

		public void RemoveById(System.Guid id)
		{
			object parameters = new { id };
			var sql = DeleteQueryBy + WhereQueryById;
			DataAccessService.PersistObject<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters);
		}
		public async Task RemoveByIdAsync(System.Guid id)
		{
			object parameters = new { id };
			var sql = DeleteQueryBy + WhereQueryById;
			await DataAccessService.PersistObjectAsync<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters);
		}

		/*
		public void RemoveByCountryAndCity(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
		var sql = DeleteQueryBy + WhereQueryByCountryAndCity; 
		DataAccessService.PersistObject(address, sql);
		}
		public async Task RemoveByCountryAndCityAsync(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
		var sql = DeleteQueryBy + WhereQueryByCountryAndCity; 
		await DataAccessService.PersistObjectAsync(address, sql);
		}

		public void RemoveByCountryAndCity(string country, string city)
		{
		object parameters = new {country, city};
		var sql = DeleteQueryBy + WhereQueryByCountryAndCity; 
		DataAccessService.PersistObject<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters);
		}
		public async Task RemoveByCountryAndCityAsync(string country, string city)
		{
		object parameters = new {country, city};
		var sql = DeleteQueryBy + WhereQueryByCountryAndCity; 
		await DataAccessService.PersistObjectAsync<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters);
		}


		*//*
		public void RemoveByCountryAndCityAndZipCode(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
		var sql = DeleteQueryBy + WhereQueryByCountryAndCityAndZipCode; 
		DataAccessService.PersistObject(address, sql);
		}
		public async Task RemoveByCountryAndCityAndZipCodeAsync(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
		var sql = DeleteQueryBy + WhereQueryByCountryAndCityAndZipCode; 
		await DataAccessService.PersistObjectAsync(address, sql);
		}

		public void RemoveByCountryAndCityAndZipCode(string country, string city, string zipCode)
		{
		object parameters = new {country, city, zipCode};
		var sql = DeleteQueryBy + WhereQueryByCountryAndCityAndZipCode; 
		DataAccessService.PersistObject<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters);
		}
		public async Task RemoveByCountryAndCityAndZipCodeAsync(string country, string city, string zipCode)
		{
		object parameters = new {country, city, zipCode};
		var sql = DeleteQueryBy + WhereQueryByCountryAndCityAndZipCode; 
		await DataAccessService.PersistObjectAsync<TestRepositoryGeneration.DataObjects.BaseRepositories.Address>(sql, parameters);
		}


		*/
		/*
		public void InsertOrUpdate(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
		DataAccessService.ExecuteScalar(InsertOrUpdateQuery,address);
		}
		public async Task InsertOrUpdateAsync(TestRepositoryGeneration.DataObjects.BaseRepositories.Address address)
		{
		await DataAccessService.ExecuteScalarAsync<TestRepositoryGeneration.DataObjects.BaseRepositories.Address >(InsertOrUpdateQuery,address);
		}

		*/

	}
}
