//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YumaPos.Server.Infrastructure.Repositories
using TestRepositoryGeneration;
using YumaPos.Server.Data.Sql.Taxes;
using YumaPos.Server.Data.Sql;



namespace TestRepositoryGeneration
{
public partial class MenuItemRepository : RepositoryBase,IMenuItemRepository
{
private MenuItemСacheRepository _menuItemСacheRepository;
private MenuItemVersionRepository _menuItemVersionRepository;
private MenuItemToTaxСacheRepository _menuItemToTaxСacheRepository;
private MenuItemToTaxVersionRepository _menuItemToTaxVersionRepository;
private TaxCashRepository _taxСacheRepository;


public MenuItemRepository(YumaPos.FrontEnd.Infrastructure.Configuration.IDataAccessService dataAccessService) : base(dataAccessService)
{
_menuItemСacheRepository = new MenuItemСacheRepository(dataAccessService);
_menuItemVersionRepository = new MenuItemVersionRepository(dataAccessService);
_menuItemToTaxСacheRepository = new MenuItemToTaxСacheRepository(dataAccessService);
_menuItemToTaxVersionRepository = new MenuItemToTaxVersionRepository(dataAccessService);
_taxСacheRepository = new TaxCashRepository(dataAccessService);
}

public IEnumerable<YumaPos.Server.Infrastructure.DataObjects.MenuItem> GetAll(Boolean? isDeleted = false)
{
return _menuItemСacheRepository.GetAll(Boolean? isDeleted = false);
}
public async Task<IEnumerable<YumaPos.Server.Infrastructure.DataObjects.MenuItem>> GetAllAsync(Boolean? isDeleted = false)
{
return await _menuItemСacheRepository.GetAllAsync(Boolean? isDeleted = false);
}

/*
public IEnumerable<YumaPos.Server.Infrastructure.DataObjects.MenuItem> GetByModifiedBy(Guid  modifiedBy, Boolean? isDeleted = false)
{
return await _menuItemСacheRepository.GetByModifiedBy(Guid  modifiedBy, Boolean? isDeleted = false);
}
public async Task<IEnumerable<YumaPos.Server.Infrastructure.DataObjects.MenuItem>> GetByModifiedByAsync(Guid  modifiedBy, Boolean? isDeleted = false)
{
return await _menuItemСacheRepository.GetByModifiedByAsync(Guid  modifiedBy, Boolean? isDeleted = false);
}

*/
public void Insert(YumaPos.Server.Infrastructure.DataObjects.MenuItem menuItem)
{
menuItem.Modified = DateTimeOffset.Now;
menuItem. = _menuItemVersionRepository.Insert(menuItem);
_menuItemСacheRepository.Insert(menuItem);
}
public async Task InsertAsync(YumaPos.Server.Infrastructure.DataObjects.MenuItem menuItem)
{
menuItem.Modified = DateTimeOffset.Now;
menuItem. = _menuItemVersionRepository.InsertAsync(menuItem);
await _menuItemСacheRepository.InsertAsync(menuItem);
}

/*
public void UpdateByModifiedBy(MenuItem menuItem)
{
menuItem.Modified = DateTimeOffset.Now;
menuItem. = _menuItemVersionRepositoryInsert(menuItem);
_menuItemСacheRepository.UpdateByModifiedBy(menuItem);
}
public async Task UpdateByModifiedByAsync(MenuItem menuItem))
{
menuItem.Modified = DateTimeOffset.Now;
menuItem. = _menuItemVersionRepositoryInsert(menuItem);
_menuItemСacheRepository.UpdateByModifiedByAsync(menuItem);
}

*/
/*
public void RemoveByModifiedBy(Guid  modifiedBy)
{
menuItem.IsDeleted = true;
_menuItemСacheRepository.UpdateModifiedBy(menuItem);
}
public async Task RemoveByModifiedByAsync(Guid  modifiedBy))
{
menuItem.IsDeleted = true;
_menuItemСacheRepository.UpdateModifiedByAsync(menuItem);
}

*/

}
}
