//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YumaPos.Server.Data.Sql;
using YumaPos.Server.Infrastructure.Repositories;



namespace TestRepositoryGeneration
{
public class MenuItemСacheRepository : RepositoryBase,IMenuItemRepository
{
public MenuItemСacheRepository(YumaPos.FrontEnd.Infrastructure.Configuration.IDataAccessService dataAccessService) : base(dataAccessService) { }
/*
Generation ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at VersionedRepositoryGeneration.Generator.Core.CodeClassGeneratorСacheRepository.GetFields() in C:\GitHub\Yumapos\Yumapos-WCF-Generator\WCF-Generator\RepositoriesGeneration\Core\CodeClassGeneratorСacheRepository.cs:line 61
   at VersionedRepositoryGeneration.Generator.Infrastructure.BaseCodeClassGeneratorRepository.GetFullCode() in C:\GitHub\Yumapos\Yumapos-WCF-Generator\WCF-Generator\RepositoriesGeneration\Infrastructure\BaseCodeClassGeneratorRepository.cs:line 102
*/
