//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using YumaPos.Server.Data.Sql;



namespace YumaPos.Server.Data.Sql.Taxes
{
public partial class TaxVersionRepository : RepositoryBase
{
private const string InsertQuery = @"INSERT INTO TaxVersionRepository([TaxId],[TaxVersionId],[Name],[Modified],[ModifiedBy],[IsDeleted])
OUTPUT INSERTED.TaxVersionIdVALUES (@TaxId,@TaxVersionId,@Name,@Modified,@ModifiedBy,@IsDeleted)";
public TaxVersionRepository(YumaPos.FrontEnd.Infrastructure.Configuration.IDataAccessService dataAccessService) : base(dataAccessService) { }
public Guid Insert(YumaPos.FrontEnd.Infrastructure.DataObjects.PosFdat.Taxes.Tax tax)
{
var res = DataAccessService.InsertObject(tax, InsertQuery);
return (Guid)res;
}
public async Task<Guid> InsertAsync(YumaPos.FrontEnd.Infrastructure.DataObjects.PosFdat.Taxes.Tax tax)
{
var res = await DataAccessService.InsertObjectAsync(tax, InsertQuery);
return (Guid)res;
}

}
}
